package dao;

import java.util.List;
import model.StudentsDomainObject;

public interface StudentDomainObjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbg.generated Sun Dec 03 13:20:06 CST 2017
     */
    int deleteByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbg.generated Sun Dec 03 13:20:06 CST 2017
     */
    int insert(StudentsDomainObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbg.generated Sun Dec 03 13:20:06 CST 2017
     */
    StudentsDomainObject selectByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbg.generated Sun Dec 03 13:20:06 CST 2017
     */
    List<StudentsDomainObject> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbg.generated Sun Dec 03 13:20:06 CST 2017
     */
    int updateByPrimaryKey(StudentsDomainObject record);
}